version: "3.9"

services:
  app:
    build: .
    container_name: geo-mro-app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: python src/mlflow_setup/dummy_run.py

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow-server
    ports:
      - "5001:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ./mlruns
      --host 0.0.0.0
