[pytest]

addopts =
    --cov=src
    --cov-report=term-missing
    --cov-fail-under=70

filterwarnings =
    ignore:legacy embedding function config.*:DeprecationWarning
    ignore:The filesystem tracking backend.*:FutureWarning
    ignore:Constructing LpVariable.*:DeprecationWarning
    ignore:Using LpProblem.constraints.*:DeprecationWarning
    ignore:The least populated class in y.*:UserWarning
