[pytest]
addopts =
    --cov=src
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=70

testpaths = tests

filterwarnings =
    ignore::pyparsing.exceptions.PyparsingDeprecationWarning
