apiVersion: v1
kind: Service

metadata:
  name: geo-aware-mro-service

spec:

  selector:
    app: geo-aware-mro-api

  ports:

    - protocol: TCP

      port: 80

      targetPort: 8000

  type: LoadBalancer
