CREATE TABLE sku_master (
    sku_id VARCHAR NOT NULL,
    item_name VARCHAR NOT NULL,
    item_description VARCHAR,
    category VARCHAR NOT NULL,
    subcategory VARCHAR,
    uom VARCHAR NOT NULL,
    abc_class VARCHAR NOT NULL,
    ved_class VARCHAR NOT NULL,
    fns_class VARCHAR NOT NULL,
    class_code VARCHAR NOT NULL,
    unit_cost_usd DOUBLE NOT NULL,
    lead_time_days INTEGER NOT NULL,
    moq INTEGER NOT NULL,
    supplier_id VARCHAR NOT NULL,
    supplier_name VARCHAR NOT NULL,
    supply_origin_country VARCHAR NOT NULL,
    geo_risk_score DOUBLE NOT NULL,
    criticality_score DOUBLE NOT NULL,
    annual_demand_qty DOUBLE NOT NULL,
    avg_monthly_demand_qty DOUBLE NOT NULL,
    demand_cv DOUBLE,
    intermittency_index DOUBLE,
    service_level_target DOUBLE NOT NULL,
    stockout_cost_usd DOUBLE NOT NULL,
    salvage_value_usd DOUBLE NOT NULL,
    current_on_hand_qty DOUBLE NOT NULL,
    reorder_point_qty DOUBLE,
    safety_stock_qty DOUBLE
);